
import groovy.json.JsonSlurper
import groovy.transform.CompileStatic

/**
 * Loader for the PORTABLE parity scenario/expected fixtures (task 8.1, R17.1).
 *
 * The parity evidence gate (D9) compares the Groovy allocator against the
 * validated Python Reference on a shared, platform-neutral fixture set. Both
 * sides consume the SAME {@code *.scenario.json}; the Reference produces the
 * matching {@code *.expected.json} (regenerated by {@code tools/gen_parity_fixtures}).
 * This class is the Groovy side of that contract: it parses a scenario into the
 * pure allocator input POGOs ({@link RoomAllocInput} / {@link AllocSettings} /
 * {@link DuctSignals} + a learned {@link Dabv2Learning.VentCurve}) and parses
 * the expected output into {@link ParityExpected}.
 *
 * <p><b>Portable scenario format</b> ({@code <id>.scenario.json}):</p>
 * <pre>
 * {
 *   "id": "overcool-drag-cooling",
 *   "mode": "cooling",                  // "cooling" | "heating"
 *   "setpointC": 26.1,
 *   "settings": { "safetyFloorPct":40, "conventionalVents":4, "conventionalOpenPct":50,
 *                 "granularity":5, "crosscoupling":true, "hysteresisC":0.3,
 *                 "airflowLimitedMarginPct":5, "airflowLimitedErrorC":0.5, "horizonMin":30,
 *                 "inactiveOpenPctSum":0, "inactiveCount":0,
 *                 "spreadGuardrailC":1.0, "spreadImprovementDeadbandC":0.3 },
 *   "rooms": [
 *     { "roomId":"mariana", "tempC":27.9, "active":true, "efficiency":0.017, "leak":0.10,
 *       "currentOpen":100, "ventIds":["v_mariana"], "signedErrorC":1.8,
 *       "curve": { "breakpoints":[0,5,...,100], "flow":[0.10,...,1.0], "counts":[...] } }
 *   ],
 *   "duct": null                        // or { "ductTempC":12.0, "ductPressurePa":40 }
 * }
 * </pre>
 *
 * <p><b>Expected format</b> ({@code <id>.expected.json}) — Reference-generated:</p>
 * <pre>
 * { "id":"overcool-drag-cooling", "targets":{...}, "predictedSpreadC":1.2,
 *   "airflowLimited":["mariana"], "floorBinding":true, "combinedOpenPct":41.0,
 *   "referenceCommit":"&lt;hvac_vent_optimizer git sha&gt;",
 *   "tolerance":{ "aperturePoints":1 } }
 * </pre>
 *
 * Test-support code (not a pure library and not on-device), so it MAY use the
 * JVM/file APIs the pure {@code libraries/*.groovy} modules must avoid.
 */

class ParityFixtures {

  private static final Script LIB = new GroovyShell().parse(new File('libraries/flair-vents-dabv2.groovy'))

  static final String SCENARIO_SUFFIX = '.scenario.json'
  static final String EXPECTED_SUFFIX = '.expected.json'

  /**
   * Resolve the parity fixtures directory. Gradle runs the test task with the
   * project root as the working directory, so the harness layout path
   * {@code tests/resources/parity} resolves directly; a couple of fallbacks
   * keep the loader robust to being launched from a sub-directory or to the
   * design's {@code test/resources/parity} spelling.
   */
  static File dir() {
    List<String> candidates = [
      'tests/resources/parity',
      'test/resources/parity',
      'hubitat-flair-vents/tests/resources/parity',
    ]
    for (String c : candidates) {
      File f = new File(c)
      if (f.isDirectory()) {
        return f.getAbsoluteFile()
      }
    }
    // Fall back to the conventional location even if not yet created, so callers
    // get a meaningful path in assertion messages.
    return new File('tests/resources/parity').getAbsoluteFile()
  }

  /** Sorted list of scenario ids discovered under {@link #dir()}. */
  static List<String> scenarioIds() {
    File d = dir()
    File[] files = d.listFiles()
    List<String> ids = new ArrayList<String>()
    if (files != null) {
      for (File f : files) {
        String name = f.getName()
        if (name.endsWith(SCENARIO_SUFFIX)) {
          ids.add(name.substring(0, name.length() - SCENARIO_SUFFIX.length()))
        }
      }
    }
    Collections.sort(ids)
    return ids
  }

  static File scenarioFile(String id) {
    return new File(dir(), id + SCENARIO_SUFFIX)
  }

  static File expectedFile(String id) {
    return new File(dir(), id + EXPECTED_SUFFIX)
  }

  /** Parse {@code <id>.scenario.json} into the pure allocator input POGOs. */
  static ParityScenario loadScenario(String id) {
    Map json = parse(scenarioFile(id))
    ParityScenario sc = new ParityScenario()
    sc.id = str(json.get('id'), id)
    sc.mode = str(json.get('mode'), 'cooling')
    sc.setpointC = dbl(json.get('setpointC'), 0.0d)
    sc.settings = toSettings((Map) json.get('settings'))
    sc.duct = toDuct(json.get('duct'))
    sc.rooms = toRooms((List) json.get('rooms'), sc.mode, sc.setpointC)
    return sc
  }

  /** Parse {@code <id>.expected.json} (Reference-generated) into {@link ParityExpected}. */
  static ParityExpected loadExpected(String id) {
    Map json = parse(expectedFile(id))
    ParityExpected ex = new ParityExpected()
    ex.id = str(json.get('id'), id)
    ex.targets = toDoubleMap((Map) json.get('targets'))
    ex.predictedSpreadC = json.get('predictedSpreadC') == null ? null :
      Double.valueOf(dbl(json.get('predictedSpreadC'), 0.0d))
    ex.airflowLimited = toStringSet((List) json.get('airflowLimited'))
    ex.floorBinding = bool(json.get('floorBinding'), false)
    ex.combinedOpenPct = json.get('combinedOpenPct') == null ? null :
      Double.valueOf(dbl(json.get('combinedOpenPct'), 0.0d))
    ex.referenceCommit = str(json.get('referenceCommit'), '')
    Object tol = json.get('tolerance')
    int points = 1
    if (tol instanceof Map) {
      points = (int) dbl(((Map) tol).get('aperturePoints'), 1.0d)
    }
    ex.toleranceAperturePoints = points
    return ex
  }

  /**
   * Expand a per-ROOM target map into a per-VENT device map (R15.4) so a test
   * can compute {@link Dabv2SafetyFloor#combinedOpenPct} the same way
   * the floor does internally. Active rooms always contribute their vents;
   * inactive rooms contribute only while held open ({@code pct > 0}, R6.7).
   */
  static Map<String, Double> expandPerVent(Map<String, Double> targets, List rooms) {
    Map byId = new LinkedHashMap()
    for (Map r : rooms) {
      if (r != null && r.roomId != null) {
        byId.put(r.roomId, r)
      }
    }
    Map<String, Double> perVent = new LinkedHashMap<String, Double>()
    for (Map.Entry<String, Double> e : targets.entrySet()) {
      Map r = byId.get(e.key)
      double pct = e.value == null ? 0.0d : e.value.doubleValue()
      if (r == null) {
        perVent.put(e.key, pct)
        continue
      }
      if (!r.active && pct <= 0.0d) {
        continue
      }
      if (r.ventIds != null && !r.ventIds.isEmpty()) {
        for (String vid : r.ventIds) {
          perVent.put(vid, pct)
        }
      } else {
        perVent.put(e.key, pct)
      }
    }
    return perVent
  }

  // ---------------------------------------------------------------------------
  // Parsing helpers.
  // ---------------------------------------------------------------------------

  private static Map parse(File f) {
    if (!f.isFile()) {
      throw new IllegalStateException("Parity fixture not found: ${f.getAbsolutePath()}")
    }
    Object parsed = new JsonSlurper().parse(f, 'UTF-8')
    if (!(parsed instanceof Map)) {
      throw new IllegalStateException("Parity fixture is not a JSON object: ${f.getAbsolutePath()}")
    }
    return (Map) parsed
  }

  private static Map toSettings(Map m) {
    Map s = LIB.dabv2NewAllocSettings()
    if (m == null) {
      return s
    }
    if (m.containsKey('safetyFloorPct')) { s.safetyFloorPct = dbl(m.get('safetyFloorPct'), s.safetyFloorPct) }
    if (m.containsKey('conventionalVents')) { s.conventionalVents = (int) dbl(m.get('conventionalVents'), s.conventionalVents) }
    if (m.containsKey('conventionalOpenPct')) { s.conventionalOpenPct = dbl(m.get('conventionalOpenPct'), s.conventionalOpenPct) }
    if (m.containsKey('inactiveOpenPctSum')) { s.inactiveOpenPctSum = dbl(m.get('inactiveOpenPctSum'), s.inactiveOpenPctSum) }
    if (m.containsKey('inactiveCount')) { s.inactiveCount = (int) dbl(m.get('inactiveCount'), s.inactiveCount) }
    if (m.containsKey('granularity')) { s.granularity = (int) dbl(m.get('granularity'), s.granularity) }
    if (m.containsKey('crosscoupling')) { s.crosscoupling = bool(m.get('crosscoupling'), s.crosscoupling) }
    if (m.containsKey('hysteresisC')) { s.hysteresisC = dbl(m.get('hysteresisC'), s.hysteresisC) }
    if (m.containsKey('airflowLimitedMarginPct')) { s.airflowLimitedMarginPct = dbl(m.get('airflowLimitedMarginPct'), s.airflowLimitedMarginPct) }
    if (m.containsKey('airflowLimitedErrorC')) { s.airflowLimitedErrorC = dbl(m.get('airflowLimitedErrorC'), s.airflowLimitedErrorC) }
    if (m.containsKey('horizonMin')) { s.horizonMin = dbl(m.get('horizonMin'), s.horizonMin) }
    if (m.containsKey('spreadGuardrailC')) { s.spreadGuardrailC = dbl(m.get('spreadGuardrailC'), s.spreadGuardrailC) }
    if (m.containsKey('spreadImprovementDeadbandC')) { s.spreadImprovementDeadbandC = dbl(m.get('spreadImprovementDeadbandC'), s.spreadImprovementDeadbandC) }
    return s
  }

  private static Map toDuct(Object o) {
    if (!(o instanceof Map)) {
      return null
    }
    Map m = (Map) o
    Map d = [:]
    if (m.get('ductTempC') != null) { d.ductTempC = Double.valueOf(dbl(m.get('ductTempC'), 0.0d)) }
    // The Reference duct-pressure field is `ductPressurePa`; the Groovy POGO
    // calls it `ductPressure`. Accept either spelling so the fixture stays
    // platform-neutral.
    Object pressure = m.get('ductPressurePa') != null ? m.get('ductPressurePa') : m.get('ductPressure')
    if (pressure != null) { d.ductPressure = Double.valueOf(dbl(pressure, 0.0d)) }
    return d
  }

  private static List toRooms(List raw, String mode, double setpointC) {
    List rooms = new ArrayList()
    if (raw == null) {
      return rooms
    }
    boolean heating = mode != null && mode.toLowerCase().contains('heat')
    for (Object o : raw) {
      if (!(o instanceof Map)) {
        continue
      }
      Map m = (Map) o
      Map r = [:]
      r.roomId = str(m.get('roomId'), null)
      r.tempC = dbl(m.get('tempC'), 0.0d)
      r.active = bool(m.get('active'), false)
      r.efficiency = dbl(m.get('efficiency'), 0.0d)
      r.leak = dbl(m.get('leak'), 0.0d)
      r.currentOpen = dbl(m.get('currentOpen'), 0.0d)
      r.ventIds = toStringList((List) m.get('ventIds'))
      // signedErrorC: prefer the explicit fixture value; otherwise derive it from
      // temp/setpoint/mode EXACTLY as the Reference does, so both sides bias the
      // safety floor identically (parity-safe default).
      if (m.get('signedErrorC') != null) {
        r.signedErrorC = dbl(m.get('signedErrorC'), 0.0d)
      } else {
        r.signedErrorC = heating ? (setpointC - r.tempC) : (r.tempC - setpointC)
      }
      Object curve = m.get('curve')
      if (curve instanceof Map) {
        r.curve = LIB.lrnVentCurveFromMap(curve)
      }
      rooms.add(r)
    }
    return rooms
  }

  private static Map<String, Double> toDoubleMap(Map m) {
    Map<String, Double> out = new LinkedHashMap<String, Double>()
    if (m != null) {
      for (Object k : m.keySet()) {
        out.put(k.toString(), Double.valueOf(dbl(m.get(k), 0.0d)))
      }
    }
    return out
  }

  private static List<String> toStringList(List raw) {
    List<String> out = new ArrayList<String>()
    if (raw != null) {
      for (Object o : raw) {
        if (o != null) {
          out.add(o.toString())
        }
      }
    }
    return out
  }

  private static Set<String> toStringSet(List raw) {
    Set<String> out = new LinkedHashSet<String>()
    out.addAll(toStringList(raw))
    return out
  }

  private static double dbl(Object o, double dflt) {
    if (o instanceof Number) {
      return ((Number) o).doubleValue()
    }
    if (o instanceof CharSequence) {
      try {
        return Double.parseDouble(o.toString())
      } catch (NumberFormatException ignored) {
        return dflt
      }
    }
    return dflt
  }

  private static boolean bool(Object o, boolean dflt) {
    if (o instanceof Boolean) {
      return ((Boolean) o).booleanValue()
    }
    if (o instanceof CharSequence) {
      return Boolean.parseBoolean(o.toString())
    }
    return dflt
  }

  private static String str(Object o, String dflt) {
    return o == null ? dflt : o.toString()
  }
}
